[project]
name = "karaoke-utils"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "openpyxl>=3.1.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
]

[tool.ruff]
line-length = 120
